django/장고유저랑글이랑댓글연결/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

django/장고유저랑글이랑댓글연결/community/urls.py
from django.urls import path
from . import views

app_name = 'community'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/comments/', views.comments_create, name='comments_create'),
]

django/장고유저랑글이랑댓글연결/pjt06/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('community/', include('community.urls')),
]

django/장고유저랑글이랑댓글연결/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

django/장고유저랑글이랑댓글연결/community/models.py
from django.db import models
from pjt06 import settings

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100)
    movie_title = models.CharField(max_length=50)
    rank = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.CharField(max_length=100)
    review_id = models.ForeignKey(Review, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

django/장고유저랑글이랑댓글연결/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth import get_user_model
from django import forms


class CustomUserCreationForm(UserCreationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'autofocus': True,
                }
            )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'autocomplete': 'new-password',
                }
            )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'autocomplete': 'new-password',
                }
            )
    )
    email = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    first_name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    last_name = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

class CustomAuthenticationForm(AuthenticationForm):
    username = UsernameField(
        label = 'id',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'autofocus': True,
                }
            )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'autocomplete': 'new-password',
                }
            )
    )
    class Meta:
        model = get_user_model()
        fields = '__all__'

django/장고유저랑글이랑댓글연결/community/forms.py
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '제목을 입력하세요',
            }
        )
    )
    movie_title = forms.CharField(
        label='영화 제목',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '영화의 제목을 입력하세요',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '내용을 입력하세요',
            }
        )
    )
    rank = forms.IntegerField(
        label='당신의 점수',
    )
    class Meta:
        model = Review
        fields = ('title', 'movie_title', 'content', 'rank')
        

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

django/장고유저랑글이랑댓글연결/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_http_methods
from .forms import CustomUserCreationForm, CustomAuthenticationForm

# Create your views here.
@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('community:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('community:index')

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('community:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('community:index')

django/장고유저랑글이랑댓글연결/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.views.decorators.http import require_http_methods, require_POST, require_safe

# Create your views here.
@require_safe
def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews':reviews,
    }
    return render(request, 'community/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            reviews = form.save(commit=False)
            reviews.user_id = request.user
            reviews.save()
            return redirect('community:index')
    else:
        form = ReviewForm()

    context = {
        'form':form,
    }
    return render(request, 'community/create.html', context)


@require_safe
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm()
    context = {
        'comment_form': comment_form,
        'review': review,
    }
    return render(request, 'community/detail.html', context)


@require_POST
def comments_create(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.review_id = review
            comment.user_id = request.user
            comment.save()
            return redirect('community:detail', review_pk)

        context = {
            'comment_form': comment_form,
            'review': review,
        }
        return render(request, 'community/detail.html', context)

    return redirect('accounts:login')

django/장고유저랑글이랑댓글연결/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="width: 40rem;">
        <h2>로그인</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class='btn btn-primary'>로그인</button>
        </form>
        <hr>
        <p><a href="{% url 'accounts:signup' %}">no id?</a></p>
    </div>
{% endblock content %}

django/장고유저랑글이랑댓글연결/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="container" style="width: 40rem;">
        <h2>회원가입</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class='btn btn-primary'>계정생성</button>
        </form>
        <hr>
        <p><a href="{% url 'accounts:login' %}">you have id?</a></p>
    </div>
{% endblock content %}

django/장고유저랑글이랑댓글연결/community/templates/community/create.html
{% extends 'base.html' %}

{% block content %}
    <h2>새글쓰기</h2>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn btn-primary'>세글쓰기</button>
    </form>

{% endblock content %}

django/장고유저랑글이랑댓글연결/community/templates/community/detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ review.title }}</h2>
    <h4>영화 제목 : {{ review.movie_title }}</h4>
    <br>
    <br>
    <p>{{ review.content }}</p>
    <p>점수 : {{ review.rank }}</p>
    <br>
    <br>
    <p>작성시간 : {{ review.created_at}}</p>
    <p>수정시간 : {{ review.updated_at}}</p>

    <hr>

    {% for comment in review.comment_set.all %}
        <p>{{ comment.content }}</p>
    {% endfor %}
    <hr>
    {% if user.is_authenticated %}
        <form action="{% url 'community:comments_create' review.pk %}" method="POST">
            {% csrf_token %}
            {{comment_form.as_p }}
                <button class='btn btn-primary'>세글쓰기</button>
        </form>
    {% else %}
        <p><a href="{% url 'accounts:login' %}">댓글을 쓰려면 로그인하세요</a></p>
    {% endif %}

{% endblock content %}

django/장고유저랑글이랑댓글연결/community/templates/community/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>리뷰</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">영화제목</th>
      <th scope="col">제목</th>
      <th scope="col">내용</th>
      <th scope="col">작성시간</th>
    </tr>
  </thead>
  <tbody>
    {% for review in reviews %}
    <tr>
      <th scope="row">{{ review.pk }}</th>
      <td>{{ review.movie_title }}</td>
      <td><a href="{% url 'community:detail' review.pk %}">{{ review.title }}</a></td>
      <td>{{ review.content }}</td>
      <td>{{ review.created_at }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

django/장고유저랑글이랑댓글연결/pjt06/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'community:index' %}">Pjt06</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">어서오세요! {{ request.user }}님!</a>
            </li>
            <li class="nav-item">
              <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-outline-secondary nav-link">로그아웃</button>
              </form>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'community:create' %}">새글작성</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>  
</body>
</html>