django/django_static_media/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/django_static_media/django_form/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/django_static_media/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

django/django_static_media/articles/forms.py
from django import forms
from .models import Article


# html form tag 생성
# 유효성 검사

# class ArticleForm(forms.Form):
#     REGIONS = [
#         ('daejeon', '대전'),
#         ('seoul', '서울'),
#         ('busan', '부산'),
#     ]
#     title = forms.CharField(max_length=10)
#     content = forms.CharField(widget=forms.Textarea)
#     region = forms.ChoiceField(choices=REGIONS, widget=forms.RadioSelect)
## 얘는 우리가 작성한 모델과 연관이 없을 수 있음!!

#################################################

## 얘는 모델과 연관 있음
class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '제목을 입력하세요',
            }
        )
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '내용을 입력하세요',
            }
        )
    )

    class Meta:
        model = Article
        fields = '__all__'
        # fields = ('title', 'content')

        # widgets = {
        #     'title': forms.TextInput(attrs={
        #         'class': 'form-control my-title',
        #         'placeholder': '제목을 입력하세요',
        #     }),
        #     'content': forms.Textarea(attrs={
        #         'class': 'form-control',
        #         'placeholder': '내용을 입력하세요',
        #     }),
        # }
    

django/django_static_media/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm
from django.views.decorators.http import require_http_methods


# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles
    }

    return render(request, 'articles/index.html', context)


def detail(request, pk):
    # article = Article.objects.get(pk=pk)
    article = get_object_or_404(Article, pk=pk)  # 에러날땐 404페이지를 띄워라
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


# new랑 create 합체
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':  # create
        form = ArticleForm(request.POST, request.FILES)  # media를 위해 내용 추가
        if form.is_valid:
            article = form.save()  # form.save()는 반환값이 있다.
            return redirect('articles:index')
        return redirect('articles:create')

    else:  # new
        form = ArticleForm()
        context = {
            'form': form,
        }

        return render(request, 'articles/new.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, pk):
    # article = Article.objects.get(pk=pk)
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        # modelform클래스로 인스턴스 생성
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk)
    else:
        # 위의 article을 인스턴스로 form에 넣음
        form = ArticleForm(instance=article)  # create와의 차이점
    # create도 이런 식으로 안정적으로 개선할 수 있음!!!
    context = {
        'form': form,
    }
    return render(request, 'articles/edit.html', context)


def delete(request, pk):
    # article = Article.objects.get(pk=pk)
    article = get_object_or_404(Article, pk=pk)

    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', pk)

django/django_static_media/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>detail</h1>
<h2>{{ article.title }}</h2>
<p>{{ article.content }}</p>
{% if article.image %}
  <p>{{ article.image }}</p>
  <img src="{{ article.image.url }}" alt="">
{% endif %}
<hr>
<a href="{% url 'articles:update' article.pk %}">수정</a>
<form action="{% url 'articles:delete' article.pk %}" method='POST'>
    {% csrf_token %}
    <button>삭제🗑</button>
</form>

{% endblock %}

django/django_static_media/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
    <h2>Edit</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn btn-primary'>수정</button>
    </form>
    
{% endblock  %}

django/django_static_media/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<img src="{% static 'articles/unnamed.jpg' %}" alt="">

<table class="table">
  <thead>
    <h2>모든 게시글 조회</h2>
    <br>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">제목</th>
      <th scope="col">내용</th>
      <th scope="col">작성시간</th>
    </tr>
  </thead>
  <tbody>
    {% for article in articles %}
    <tr>
      <th scope="row">{{ article.pk }}</th>
      <td><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></td>
      <td>{{ article.content }}</td>
      <td>{{ article.create_at }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

django/django_static_media/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
    <h2>New article</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class='btn btn-primary'>제출</button>
    </form>
    
{% endblock  %}

django/django_static_media/django_form/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width={device-width}, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}">
    {% block css %}
    {% endblock css %}    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'articles:index' %}">게시판</a>
            <a class="nav-link" href="{% url 'articles:create' %}">새글작성</a>
        </div>
        </div>
    </div>
    </nav>
    <h1 class="title-color">제목 색깔</h1>
    {% comment %} <img src="{% static 'images/unnamed.jpg' %}" alt=""> {% endcomment %}
    <div class='container'>
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>