django/django_crud/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),  # R
    path('new/', views.new, name='new'),  # C
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),  # R

    # 여기까지
    path('<int:pk>/edit/', views.edit, name='edit'),  # U
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),  # D
]

django/django_crud/pjt04/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

django/django_crud/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Read
def index(request):
    movies = Movie.objects.all()  # 모든 영화 정보 내놔
    context = {
        'movies': movies,
    }
    
    return render(request, 'movies/index.html', context)


# Create
def new(request):
    return render(request, 'movies/new.html')


def create(request):
    title = request.POST.get('title')
    overview = request.POST.get('overview')
    poster_path = request.POST.get('poster_path')  # 받아온 정보들로

    movie = Movie(title=title, overview=overview, poster_path=poster_path)  # 새로운 Movie생성
    movie.save()

    return redirect('movies:index')


# Read
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)  # 해당 pk의 글만 불러옴
    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


## 여기까지
# Update
def edit(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/edit.html', context)


def update(request, pk):
    movie = Movie.objects.get(pk=pk)  # 해당 글을 불러와서 

    title = request.POST.get('title')
    overview = request.POST.get('overview')
    poster_path = request.POST.get('poster_path')

    movie.title = title
    movie.overview = overview
    movie.poster_path = poster_path  # 새 정보로 업데이트
    movie.save()

    return redirect('movies:detail', movie.pk)


# Delete
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)  # 해당 pk의 글을 

    if request.method == 'POST': # 포스트방식 입력이라면 삭제
        movie.delete()
        return redirect('movies:index')
    else:
        return redirect('movies:detail', pk)

django/django_crud/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>{{ movie.title }}</h2>
  <p>{{ movie.overview }}</p>
  <p>{{ movie.poster_path }}</p>
  <img src="{{ movie.poster_path }}" class="card-img-top" alt="...">
  <br>
  <a href="{% url 'movies:edit' movie.pk %}">
  <button type="button" class="btn btn-primary">수정</button>
  </a>
  <form action="{% url 'movies:delete' movie.pk %}" method='POST'>
    {% csrf_token %}
    <button class="btn btn-danger">삭제</button>
  </form>
</div>
{% endblock %}

django/django_crud/movies/templates/movies/edit.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:update' movie.pk %}" method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" name="title" id="title" value="{{ movie.title }}" maxlength=100>
  </div>
  <div class="mb-3">
    <label for="overview" class="form-label">overview</label>
    <textarea name="overview" id="overview" class="form-control">{{ movie.overview }}</textarea>
  </div>
  <div class="mb-3">
    <label for="poster_path" class="form-label">poster_path</label>
    <input type="text" class="form-control" name="poster_path" id="poster_path" value="{{ movie.poster_path }}" maxlength=500>
  </div>
  <button type="submit" class="btn btn-primary">수정</button>
</form>
{% endblock %}

django/django_crud/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <div class='row'>
            {% for movie in movies %}
                <div class="col-4">  <!--이건 부투스트랩에서 가져옴-->
                    <div class="card" style="width: 18rem;">
                        <img src="{{ movie.poster_path }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ movie.title }}</h5>
                            <p class="card-text"> {{ movie.overview|truncatechars:20 }} </p>
                            <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-primary">보기</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

django/django_crud/movies/templates/movies/new.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'movies:create' %}" method="POST">  <!--이건 부투스트랩에서 가져옴-->
  {% csrf_token %}
  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" name="title" id="title" maxlength=100>
  </div>
  <div class="mb-3">
    <label for="overview" class="form-label">overview</label>
    <textarea name="overview" id="overview" class="form-control"></textarea>
  </div>
  <div class="mb-3">
    <label for="poster_path" class="form-label">poster_path</label>
    <input type="text" class="form-control" name="poster_path" id="poster_path" maxlength=500>
  </div>
  <button type="submit" class="btn btn-primary">작성</button>
</form>
{% endblock %}